### ISSUE TITLE
'Similarity' object has no attribute 'normalize

### ISSUE THREAD

**Issue by StevenLOL** [RaRe-Technologies/gensim-simserver#10]
Hi, I am testing this server with the latest gensim, and got the following error:

```
/usr/local/lib/python2.7/dist-packages/simserver-0.1.4-py2.7.egg/simserver/simserver.pyc in sims_by_vec(self, vec, normalize)
    236         """
    237         if normalize is None:
--> 238             normalize = self.qindex.normalize
    239         norm, self.qindex.normalize = self.qindex.normalize, normalize # store old value
    240         self.qindex.num_best = self.topsims

AttributeError: 'Similarity' object has no attribute 'normalize'
```

So I suppose is due to the upgrade in Gensim,can help to upgrade Simserver ?

I changed the self.qindex.normalize to self.qindex.norm , works for me , but not sure whether it is correct ?

**Comment by piskvorky** [comment]
Hi @StevenLOL , unfortunately simserver is no longer supported as open source.

We stopped the open source development 4 years ago. We only build such systems as commercial applications now.

So it's not kept up to date with gensim.
