### ISSUE TITLE
Loading and saving indexes to an HDFS filesystem

### ISSUE THREAD

**Issue by sauravbiswasiupr** [RaRe-Technologies/gensim-simserver#8]
Hi Radim,
Is there a way to load and save indexes to/from an HDFS filesystem (preferably on a remote cluster) instead of the local filesystem ? I googled and found no documentation regarding this functionality. would be great to have some pointers in this direction.

**Comment by piskvorky** [comment]
The indexes are memory-mapped from disk for performance, so remote storage doesn't make sense. 

Even if you could somehow "fake" the mmap, the performance would be atrocious.

**Comment by sauravbiswasiupr** [comment]
Hi, sorry for the late reply. Actually you are right. There would be no added advantage if I tried to load the indexes from HDFS or an NFS based filesystem, compared to loading them from the local filesystem. Closing this issue now.
