### ISSUE TITLE
Can apache solr use with SimServer?

### ISSUE THREAD

**Issue by semihamakinist** [RaRe-Technologies/gensim-simserver#9]
Hi Radim,
I'm acomputer engineer and my name is Semiha. I'm working about document similarity. I want to learn something from you about simServer.I'm indexing to my local File System with alache solr of my documents and  storing on it. I want to use this index documents for calculating similarty by simServer. Can I do this with SimServer? Does it allow this?

Thank you very much in advance for your help.
Have a good work and a nice day.

**Comment by piskvorky** [comment]
Hello, definitely possible, but that is an advance task that would need a better communication medium than "github issues" to explain.

Unfortunately simserver is no longer supported as open source. If you have a commercial request, please contact us at rare-technologies.com.

Best of luck,
Radim

**Comment by semihamakinist** [comment]
Hi Radim,
I combined simserver and solr and I test it. It's running.

Thank you a lot for your attention.

Best of luck,
Semiha Makinist.

**Comment by piskvorky** [comment]
Good to hear!

Can you put a link to your solution here, so that other people who google up this issue will have some guidance?

**Comment by semihamakinist** [comment]
Yes, of course, link is [here](https://gist.github.com/semihamakinist/a4bedb1d2ff37bf8f92d910a72371e8d)

take care of yourself!
